# Utiliser une image de Node.js comme base
FROM node:16

# Créer et définir le répertoire de travail de l'application
WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances avec l'option --force pour bcrypt
RUN npm install --force

# Rebuild bcrypt pour s'assurer qu'il est compilé pour l'environnement Linux
RUN npm rebuild bcrypt --build-from-source

# Exécuter prisma generate pour générer les fichiers de client Prisma
COPY ./prisma prisma

RUN npx prisma generate
# Copier le reste des fichiers de l'application
COPY . .

# Copier les fichiers nécessaires
COPY ./src/public/posts /app/public/posts
COPY uploads /app/uploads

# Exposer le port sur lequel l'application va tourner
EXPOSE 3000

# Définir la commande pour lancer l'application
CMD ["node", "app.js"]
