# Utilisez une image de Node.js
FROM node:16

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

COPY ./src/public/posts  /app/public/posts

COPY uploads  /app/uploads
EXPOSE 3000

CMD [ "node", "app.js" ]
